name: react_material_ui
version: 0.0.1
description: ReactJS Material UI Components for Dart
homepage: https://github.com/alademann/react_material_ui
authors:
  - Aaron Lademann <aaron.lademann@gmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  js: ^0.6.1+1
  json_annotation: any
  json_serializable: ^2.0.0
  over_react: ^3.1.5
  react: ^5.2.1

dev_dependencies:
  build_runner: ^1.7.1
  pedantic: ^1.8.0

dependency_overrides:
  react:
    path: /Users/aaronlademann/.publink/react
